// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.query.sql

package user

import (
	"context"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (username, email, phone_number, first_name, last_name, hash_password) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, email, phone_number, username, first_name, last_name, hash_password, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	HashPassword string `json:"hash_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.Username,
		arg.Email,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.HashPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUser = `-- name: GetUser :one
SELECT id, email, phone_number, username, first_name, last_name, hash_password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, GetUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUserByUserName = `-- name: GetUserByUserName :one
SELECT id, email, phone_number, username, first_name, last_name, hash_password, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByUserName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, email, phone_number, username, first_name, last_name, hash_password, created_at, updated_at FROM users WHERE username = $1 OR email = $1
`

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, GetUserByUsernameOrEmail, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, email, phone_number, username, first_name, last_name, hash_password, created_at, updated_at FROM users ORDER BY id LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg *ListUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PhoneNumber,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.HashPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ValidateUserPasswordByUserName = `-- name: ValidateUserPasswordByUserName :one
SELECT id, email, phone_number, username, first_name, last_name, hash_password, created_at, updated_at FROM users WHERE (username = $1 OR email = $1) AND hash_password = $2
`

type ValidateUserPasswordByUserNameParams struct {
	Username     string `json:"username"`
	HashPassword string `json:"hash_password"`
}

// DEPRECATED: This query has a SQL injection vulnerability. Use GetUserByUsernameOrEmail instead.
func (q *Queries) ValidateUserPasswordByUserName(ctx context.Context, arg *ValidateUserPasswordByUserNameParams) (*User, error) {
	row := q.db.QueryRow(ctx, ValidateUserPasswordByUserName, arg.Username, arg.HashPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.HashPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
