// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	GetUser(ctx context.Context, id int64) (*User, error)
	GetUserByUserName(ctx context.Context, username string) (*User, error)
	GetUserByUsernameOrEmail(ctx context.Context, username string) (*User, error)
	ListUsers(ctx context.Context, arg *ListUsersParams) ([]*User, error)
	// DEPRECATED: This query has a SQL injection vulnerability. Use GetUserByUsernameOrEmail instead.
	ValidateUserPasswordByUserName(ctx context.Context, arg *ValidateUserPasswordByUserNameParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
